% This function connects apparatus to bus

% Author(s): Ruiting Xu

function SimConnectPerturbation(Name_Model,Name_Bus,Name_Apparatus,Name_Perturb,ListPerturb,ApparatusType)

% Organize data
N_Apparatus = length(ListPerturb);

% Add block
for i = 1:N_Apparatus
    
    % Get the bus index of the apparatus
    Bus = ListPerturb(i);
    
    % If the apparatus is NOT a "floating bus"
    if ApparatusType{Bus}<=90
        % For ac apparatuses
        add_line(Name_Model,...
            {[Name_Apparatus{Bus} '/Lconn1'],[Name_Apparatus{Bus} '/Lconn2'],[Name_Apparatus{Bus} '/Lconn3']},...
            {[Name_Perturb{i} '/Lconn1'],[Name_Perturb{i} '/Lconn2'],[Name_Perturb{i} '/Lconn3']},...
            'autorouting','smart');
        add_line(Name_Model,...
            {[Name_Perturb{i} '/Rconn1'],[Name_Perturb{i} '/Rconn2'],[Name_Perturb{i} '/Rconn3']},...
            {[Name_Bus{Bus} '/Lconn1'],[Name_Bus{Bus} '/Lconn2'],[Name_Bus{Bus} '/Lconn3']},...
            'autorouting','smart');
    elseif 1000<=ApparatusType{i} && ApparatusType{i}<=1090  
        % For dc apparatuses
        add_line(Name_Model,...
            {[Name_Apparatus{Bus} '/Lconn1'],[Name_Apparatus{Bus} '/Lconn2']},...
            {[Name_Perturb{i} '/Lconn1'],[Name_Perturb{i} '/Lconn2']},...
            'autorouting','smart');
        add_line(Name_Model,...
            {[Name_Perturb{i} '/Rconn1'],[Name_Perturb{i} '/Rconn2']},...
            {[Name_Bus{Bus} '/Lconn1'],[Name_Bus{Bus} '/Lconn2']},...
            'autorouting','smart');
    elseif 2000<=ApparatusType{i} && ApparatusType{i}<=2090
        % For interlink apparatuses
        % Connect to ac bus
        add_line(Name_Model,...
            {[Name_Apparatus{Bus} '/Lconn1'],[Name_Apparatus{Bus} '/Lconn2'],[Name_Apparatus{Bus} '/Lconn3']},...
            {[Name_Perturb{i} '/Lconn1'],[Name_Perturb{i} '/Lconn2'],[Name_Perturb{i} '/Lconn3']},...
            'autorouting','smart');
        add_line(Name_Model,...
            {[Name_Perturb{i} '/Rconn1'],[Name_Perturb{i} '/Rconn2'],[Name_Perturb{i} '/Rconn3']},...
            {[Name_Bus{Bus} '/Lconn1'],[Name_Bus{Bus} '/Lconn2'],[Name_Bus{Bus} '/Lconn3']},...
            'autorouting','smart');
        % Connect to dc bus
        add_line(Name_Model,...
            {[Name_Apparatus{Bus} '/Lconn1'],[Name_Apparatus{Bus} '/Lconn2']},...
            {[Name_Perturb{i} '/Lconn1'],[Name_Perturb{i} '/Lconn2']},...
            'autorouting','smart');
        add_line(Name_Model,...
            {[Name_Perturb{i} '/Rconn1'],[Name_Perturb{i} '/Rconn2']},...
            {[Name_Bus{Bus} '/Lconn1'],[Name_Bus{Bus} '/Lconn2']},...
            'autorouting','smart');
    end
    
end

end